# Generated by Django 5.1.5 on 2025-02-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_example", "0002_roster_created_at_roster_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
